# Generated by Django 5.2.14 on 2026-05-31 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninja', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ninga',
            new_name='Ninja',
        ),
    ]
