# Generated by Django 5.2.14 on 2026-06-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninja', '0002_rename_ninga_ninja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dojo',
            name='desc',
            field=models.CharField(max_length=255),
        ),
    ]
